filePath: ./ # file store location, should replace to S3 later

spring.servlet.multipart.max-file-size: 10MB # the max. size of upload file

cloud:
  aws:
    credentials:
      access-key: AKIA3YT2OFBLHYYLSZRQ
      secret-key: Ku8uZgRXh5OKXdQG/gdXzkGJls9zNoKy5On8Ylw2
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: 6000obucket3

